### ISSUE TITLE
TravisCI now failing with SSLError error

### ISSUE THREAD

**Issue by jasnow** [atlrug/atlrug#72]
Two days ago (March 5, 2017), TravisCI started failing new builds with this error:
      SSL_connect SYSCALL returned=5 errno=0 state=unknown state (OpenSSL::SSL::SSLError)
      ./app/models/meetup_event.rb:7:in `get_next_month_events'
      ./app/controllers/content_controller.rb:35:in `load_meetings'
      ./app/controllers/content_controller.rb:9:in `meetings'
      ./features/step_definitions/web_steps.rb:18:in `/^(?:|I )follow "([^\"]*)"$/'
      features/main_page.feature:32:in `When I follow "Go to Meetings"'

This is the build URL: https://travis-ci.org/atlrug/atlrug/builds/207975812
The build runs cleanly locally.

**Comment by jasnow** [comment]
Unclear what happened but it started passing this morning:
https://travis-ci.org/atlrug/atlrug/builds/210962994
